#!/bin/bash 

nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_11_OC_preprocessed_reads/trimmed_fastq_R1_only --fastq_pattern "*.trim.fastq.gz" -resume  --outdir results_species_id
